{
 "title": "Crash x-ray",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "crash_id",
    "label": "Crash ID",
    "query": "2020-03-24_17:24:51.441665Z_f63205cf-ad5a-4ed3-89b2-85b7f606ecf7"
   },
   {
    "name": "crash_content",
    "query": "select\n  jsonb_pretty(a.single_crash::jsonb)\nfrom (\n\tselect\n\t\tjsonb_array_elements(report::jsonb->'crashes') as single_crash\n\tfrom public.report\n\twhere id in (\n\t      select report_id\n\t\t\t\tfrom crash.crash\n\t\t\t\twhere crash_id = '$crash_id'\n\t\t\t\t)\n\t) a\nwhere a.single_crash::jsonb->>'crash_id' = '$crash_id';"
   }
  ]
 },
 "panels": [
  {
   "title": "Report ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select report_id\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "title": "Process Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select process_name\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "title": "Ceph Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select ceph_version\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "title": "Cluster ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "--select 'NA';\n\n--/*\nselect cluster_id\nfrom crash.crash inner join grafana.ts_cluster on crash.crash.report_id = grafana.ts_cluster.report_id\nwhere crash_id = '$crash_id';\n--*/"
    }
   ]
  },
  {
   "title": "Crash ID",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select crash_id\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "title": "Entity Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select entity_name\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "select\n  encode(crash.crash.sig_v1, 'hex') sig_v1,\n  encode(crash.spec.sig_v2, 'hex') sig_v2\nfrom crash.crash inner join crash.spec on crash.crash.spec_id = crash.spec.id\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "title": "Raw crash report",
   "type": "text",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<pre>\n    <code>\n$crash_content\n    </code>\n</pre>"
   },
   "targets": [
    {
     "rawSql": "select\n  jsonb_pretty(a.single_crash::jsonb)\nfrom (\n\tselect\n\t\tjsonb_array_elements(report::jsonb->'crashes') as single_crash\n\tfrom public.report\n\twhere id in (\n\t      select report_id\n\t\t\t\tfrom crash.crash\n\t\t\t\twhere crash_id = '$crash_id'\n\t\t\t\t)\n\t) a\nwhere a.single_crash::jsonb->>'crash_id' = '$crash_id';"
    }
   ]
  },
  {
   "title": "Backtrace (Most recent call first)",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "select unnest(backtrace) as \"Backtrace\"\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Additional Details",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "rawSql": "with\n\tq as (\n\t\tselect\n\t\t  crash.spec.assert_func,\n\t\t  crash.spec.assert_condition,\n\t\t  assert_file,\n      assert_line,\n      assert_thread_name,\n      assert_msg,\n\t\t  os_name,\n      os_id,\n      os_version_id,\n      os_version,\n\t\t  utsname_hostname,\n      utsname_sysname,\n      utsname_release,\n      utsname_version,\n      utsname_machine,\n      io_error,\n      io_error_devname,\n      io_error_path,\n      io_error_code,\n      io_error_optype,\n      io_error_offset,\n      io_error_length\n      from crash.crash inner join crash.spec on crash.crash.spec_id = crash.spec.id\n      where crash_id = '$crash_id'\n      /*\n      select\n  encode(crash.crash.sig_v1, 'hex') sig_v1,\n  encode(crash.spec.sig_v2, 'hex') sig_v2\nfrom crash.crash inner join crash.spec on crash.crash.spec_id = crash.spec.id\nwhere crash_id = '$crash_id';\n      */\n      \n\t),\n\trj as (\n\t\tselect row_to_json(q) rj from q\n\t)\nselect je.key, je.value from rj join json_each_text(rj.rj) as je on true;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Assert Message",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "select\n  assert_msg\nfrom crash.crash\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Assert Function",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "rawSql": "select assert_func\nfrom crash.spec \n  inner join crash.crash on crash.spec.id = crash.crash.spec_id\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Assert Condition",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "select assert_condition\nfrom crash.spec \n  inner join crash.crash on crash.spec.id = crash.crash.spec_id\nwhere crash_id = '$crash_id';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}