{
 "title": "Crash spec X-ray",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sig_v2",
    "query": "a91bbf707e66015fe8e1c264c6b5e9151dc51f81f4c6f177ba158e599f0f6548"
   },
   {
    "name": "issue_id",
    "query": "select issue_id from crash.redmine_description_added\nwhere spec_id = (select id from crash.spec where sig_v2 = decode('$sig_v2', 'hex'))\nlimit 1;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\n<div style=\"font-size:20px\">\n    Crash fingerprint:\n        <div style=\"color:#32d1df\">${sig_v2}</div>\n</div>\n<br>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "First reported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select ts_first_occurrence::date::text\nfrom crash.spec_mv\nWHERE sig_v2 = decode('$sig_v2', 'hex')"
    }
   ]
  },
  {
   "title": "Last  reported",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "\nselect max(ts)::date::text\nfrom crash.crash\nINNER JOIN crash.spec on crash.spec.id = crash.crash.spec_id\nWHERE crash.spec.sig_v2 = decode('$sig_v2', 'hex')"
    }
   ]
  },
  {
   "title": "Crash count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM crash.crash\nINNER JOIN crash.spec ON spec_id = crash.spec.id\nWHERE sig_v2 = decode('$sig_v2', 'hex')\nAND $__timeFilter(ts)"
    }
   ]
  },
  {
   "title": "Affected Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "--SELECT count(*)\n\nselect\n  count(*)\nfrom (\n  SELECT\n    DISTINCT ON(cluster_id)\n    grafana.ts_cluster.*\n  from crash.crash\n  INNER JOIN crash.spec ON spec_id = crash.spec.id\n  INNER JOIN grafana.ts_cluster ON crash.crash.report_id = grafana.ts_cluster.report_id\n  WHERE sig_v2 = decode('$sig_v2', 'hex')\n  AND $__timeFilter(crash.crash.ts)\n  order by grafana.ts_cluster.cluster_id, grafana.ts_cluster.ts desc\n) as affected_clusters;"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT crash.spec_status.description as status\nFROM crash.spec\nINNER JOIN crash.spec_status on crash.spec.spec_status_id = crash.spec_status.id\nWHERE sig_v2 = decode('$sig_v2', 'hex');\n\n/*\nSELECT issue_status as status\nFROM crash.spec_to_redmine_main_issue\nINNER JOIN crash.spec on crash.spec.id = crash.spec_to_redmine_main_issue.spec_id\nWHERE sig_v2 = decode('$sig_v2', 'hex');\n*/\n"
    }
   ]
  },
  {
   "title": "Crashes by Version",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT 'v' || split_part(crash.crash.ceph_version, '-', 1) as metric, count(*)\nFROM crash.crash\nINNER JOIN crash.spec ON spec_id = crash.spec.id\nWHERE sig_v2 = decode('$sig_v2', 'hex')\nAND $__timeFilter(ts)\nGROUP BY 1\nORDER BY 1;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Stack Names (Most recent call first)",
   "type": "table",
   "description": "The stack trace of the crash without function offsets",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select UNNEST(stack_names) as functions\nfrom crash.spec\nWHERE sig_v2 = decode('$sig_v2', 'hex')\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Assert Function",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select assert_func\nfrom crash.spec_mv\nwhere sig_v2 = decode('$sig_v2', 'hex');"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Assert Condition",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "select assert_condition\nfrom crash.spec_mv\nwhere sig_v2 = decode('$sig_v2', 'hex');"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Daily Occurrences",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(ts, '1d', 0) as time, count(*)\nFROM crash.crash\nINNER JOIN crash.spec ON spec_id = crash.spec.id\nWHERE sig_v2 = decode('$sig_v2', 'hex')\nAND $__timeFilter(ts)\nGROUP BY $__timeGroup(ts, '1d', 0)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Affected Clusters",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "rawSql": "-- cluster info from a report that contains a related crash\nwith\ncluster_info as (\n\tselect\n\t  DISTINCT ON(cluster_id)\n\t  grafana.ts_cluster.*\n\tfrom crash.crash\n\tINNER JOIN crash.spec ON spec_id = crash.spec.id\n\tINNER JOIN grafana.ts_cluster ON crash.crash.report_id = grafana.ts_cluster.report_id\n\tWHERE sig_v2 = decode('$sig_v2', 'hex')\n\t--AND $__timeFilter(crash.crash.ts)\n),\nrecent_versions as (\n\t-- the latest metadata for each cluster\n\tselect gm.report_id, array_agg(distinct(gm.value)) recent_versions, gc.cluster_id \n\tfrom grafana.metadata gm inner join grafana.ts_cluster gc on gm.report_id = gc.report_id \n\twhere gm.report_id in (\n\t\tselect max(report_id) \n\t\tfrom grafana.ts_cluster \n\t\twhere cluster_id in --('2133741d-5f4e-4afd-ace3-2760b255d7c7', '0b54fcbf-aa86-4154-8290-7767a733a824')\n\t\t\t\t( select ci.cluster_id\n\t\t\t\tfrom cluster_info ci\n\t\t\t\t)\n\t\tgroup by cluster_id\n\t\t)\n\tand attr = 'ceph_version_norm'\n\tgroup by gm.report_id, gc.cluster_id \n)\nselect ci.*, rv.recent_versions \nfrom  \nrecent_versions rv\ninner join cluster_info ci on rv.cluster_id = ci.cluster_id\norder by ci.cluster_id, ci.ts desc\n\n/*\nselect\n  DISTINCT ON(cluster_id)\n  grafana.ts_cluster.*\nfrom crash.crash\nINNER JOIN crash.spec ON spec_id = crash.spec.id\nINNER JOIN grafana.ts_cluster ON crash.crash.report_id = grafana.ts_cluster.report_id\nWHERE sig_v2 = decode('$sig_v2', 'hex')\nAND $__timeFilter(crash.crash.ts)\norder by grafana.ts_cluster.cluster_id, grafana.ts_cluster.ts desc\n*/"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Crashes",
   "type": "table",
   "description": "Crashes with the same specification/fingerprint that occurred between ${__from:date:YYYY-MM-DD} and ${__to:date:YYYY-MM-DD}. Click on a crash_id to see more details (like its backtrace). ",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT \n--crash.crash.*\n  crash.crash.id,\n  crash.crash.spec_id,\n  crash.crash.crash_id,\n  crash.crash.report_id,\n  crash.crash.ts::text,\n  encode(crash.crash.sig_v1, 'hex') sig_v1,\n  crash.crash.process_name,\n  crash.crash.entity_name,\n  crash.crash.ceph_version,\n  crash.crash.utsname_hostname,\n  crash.crash.utsname_sysname,\n  crash.crash.utsname_release,\n  crash.crash.utsname_version,\n  crash.crash.utsname_machine,\n  crash.crash.os_name,\n  crash.crash.os_id,\n  crash.crash.os_version_id,\n  crash.crash.os_version,\n  crash.crash.assert_file,\n  crash.crash.assert_line,\n  crash.crash.assert_thread_name,\n  crash.crash.assert_msg,\n  crash.crash.io_error,\n  crash.crash.io_error_devname,\n  crash.crash.io_error_path,\n  crash.crash.io_error_code,\n  crash.crash.io_error_optype,\n  crash.crash.io_error_offset,\n  crash.crash.io_error_length\nFROM crash.crash\nINNER JOIN crash.spec ON spec_id = crash.spec.id\nWHERE crash.spec.sig_v2 = decode('$sig_v2', 'hex')\nAND $__timeFilter(crash.crash.ts)\nORDER BY crash.crash.ts DESC\n\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Affected Clusters Contact Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "rawSql": "--select 'NA'\n\n--/*\n--affected clusters\nwith affected_clusters as (\n\tselect\n\t  --count(*)\n\t  report_id, cluster_id\n\tfrom (\n\t\t  SELECT\n\t\t    DISTINCT ON(cluster_id)\n\t\t    grafana.ts_cluster.*\n\t\t  from crash.crash\n\t\t  INNER JOIN crash.spec ON spec_id = crash.spec.id\n\t\t  INNER JOIN grafana.ts_cluster ON crash.crash.report_id = grafana.ts_cluster.report_id\n\t\t  --WHERE spec_id in (1407)--(select * from generate_series(1,100))\n\t\t  WHERE sig_v2 = decode('$sig_v2', 'hex')\n\t\t  AND $__timeFilter(crash.crash.ts)\n\t\t  AND channel_ident\n\t\t  order by grafana.ts_cluster.cluster_id, grafana.ts_cluster.ts desc\n\t) affected_clusters\n)\nselect pr.cluster_id, --pr.id,\n\t\treplace(pr.report, E'\\\\u0000', ' ')::jsonb#>'{organization}' organization,\n\t\treplace(pr.report, E'\\\\u0000', ' ')::jsonb#>'{description}' description,\n\t\treplace(pr.report, E'\\\\u0000', ' ')::jsonb#>'{contact}' contact\nfrom affected_clusters ac\n-- inner join crash.crash cc on ac.report_id = cc.report_id \ninner join public.report pr on ac.report_id = pr.id\nwhere pr.id in (ac.report_id)\n--*/"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Redmine Issues",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "--select id from crash.spec where sig_v2 = decode('$sig_v2', 'hex');\n\n--select * from crash.redmine_description_added\nselect * from crash.spec_to_redmine_main_issue\nwhere spec_id = (select id from crash.spec where sig_v2 = decode('$sig_v2', 'hex'))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}