{
 "title": "Main",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\nThe panels in this dashboard are affected by the time range selected in the time picker (top right corner)."
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "options": {
    "content": "<br>\n<div style=\"text-align:center\">\n    <a style=\"font-size:45px;\" href='/d/Nvj6XTaMk/spec-search?'>search</a>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Distinct Crash Fingerprints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct(crash.crash.spec_id))\nFROM crash.crash\nWHERE $__timeFilter(ts)\n"
    }
   ]
  },
  {
   "title": "New Crash Fingerprints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM crash.spec_mv\nWHERE $__timeFilter(ts_first_occurrence)\n"
    }
   ]
  },
  {
   "title": "Crash Events",
   "type": "stat",
   "description": "Counts all crash events between ${__from:date:YYYY-MM-DD} and ${__to:date:YYYY-MM-DD}.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM crash.crash\nWHERE $__timeFilter(ts);\n"
    }
   ]
  },
  {
   "title": "IO Errors",
   "type": "stat",
   "description": "Counts all crash events between ${__from:date:YYYY-MM-DD} and ${__to:date:YYYY-MM-DD} that reported IO errors.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM crash.crash\nWHERE $__timeFilter(ts)\n      AND crash.crash.io_error = 'true';\n"
    }
   ]
  },
  {
   "title": "Count of fingerprints bucketed by number of crash events",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1d', 0) as time, count(*)\nFROM\n  crash.crash\nWHERE\n  $__timeFilter(ts)\nGROUP BY\n  $__timeGroup(ts, '1d', 0), spec_id\nORDER BY\n  1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Version Crashiness",
   "type": "bargauge",
   "description": "Number of crashes per daemon per major version for the whole time frame selected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "with \n  latest_report AS ( -- The latest cluster report for a specific time interval\n\tSELECT\n\t\tDISTINCT ON(cluster_id)\n\t\treport_id\n\tFROM \n\t\tgrafana.ts_cluster\n\tWHERE\n\t\t$__timeFilter(ts)\n\tORDER BY\n\t\tcluster_id,\n\t    ts DESC\n  ),\n  version_count AS (\n  -- Number of daemons running a specific version for the time frame selected above.\n\tSELECT SPLIT_PART(value, '.', 1) as version, sum(total) num\n\tFROM latest_report \n\tINNER JOIN grafana.metadata ON latest_report.report_id = grafana.metadata.report_id\n\tWHERE\n\t\tattr='ceph_version_norm'\n\tGROUP BY 1\n  ),\n  crashes_versions_count AS (\n  -- Crashes count per version per time frame.\n\tSELECT split_part(ceph_version, '.', 1) as version, count(*) num\n\tFROM crash.crash\n\tWHERE $__timeFilter(ts)\n\tGROUP BY 1\n  )\nSELECT 'v' || version_count.version::TEXT AS version,\n        coalesce(crashes_versions_count.num / version_count.num::REAL, 0) crashiness\nFROM version_count\nLEFT JOIN crashes_versions_count ON crashes_versions_count.version = version_count.version\nORDER BY version;"
    }
   ]
  },
  {
   "title": "Crash Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1d', 0) as time,\n  case when crash.crash.io_error is null then 'crashes' else 'io_error' end as metric,\n  count(*) as crash_count\nFROM\n  crash.crash\nWHERE\n  $__timeFilter(ts)\nGROUP BY\n  $__timeGroup(ts, '1d', 0),2\nORDER BY\n  1\n  "
    },
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1d', 0) as time,\n  'fingerprints' as metric,\n  count(distinct(spec_id)) as fingerprints\nFROM\n  crash.crash\nWHERE\n  $__timeFilter(ts)\nGROUP BY\n  $__timeGroup(ts, '1d', 0)\nORDER BY\n  1\n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Crash Fingerprints by Version",
   "type": "graph",
   "description": "Counts the distinct occurrences of v2 crash signatures, and aggregates them by major versions.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1d', 0) as time,\n  count(distinct(spec_id)),\n  split_part(ceph_version, '-', 1) as metric\nFROM\n  crash.crash\nWHERE\n  $__timeFilter(ts)\nGROUP BY\n  $__timeGroup(ts, '1d', 0),\n  split_part(ceph_version, '-', 1)\nORDER BY\n  1, split_part(ceph_version, '-', 1)\n  -- split_part(ceph_version, '-', 1), 1"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Crash Events by Version",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(ts, '1d', 0) as time,\n  count(*),\n  split_part(ceph_version, '-', 1) as metric\nFROM\n  crash.crash\nWHERE\n  $__timeFilter(ts)\nGROUP BY\n  $__timeGroup(ts, '1d', 0),\n  split_part(ceph_version, '-', 1)\nORDER BY\n  1, split_part(ceph_version, '-', 1); \n--  split_part(ceph_version, '-', 1), 1  "
    }
   ]
  }
 ]
}