{
 "title": "Leaderboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Leaderboard opted-in - last week",
   "type": "table",
   "description": "All clusters reporting during the last 7 days that enabled leaderboard",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "with leaderboard_clusters as (\n\t-- get all clusters that opted in to leaderboard\n\tselect \n\t\tr.id report_id,\n\t\treplace(r.report, E'\\\\u0000', ' ')::jsonb#>'{organization}' organization,\n\t\treplace(r.report, E'\\\\u0000', ' ')::jsonb#>'{description}' description,\n\t\treplace(r.report, E'\\\\u0000', ' ')::jsonb#>'{contact}' contact\n\t\t--replace(r.report, E'\\\\u0000', ' ')::jsonb ? 'leaderboard', \n\t\t--cluster_id,\n\t\t--r.report_stamp \n\tfrom public.report r\n\t-- we join the materialized view since not all clusters report daily, and mv normalizes this\n\tinner join grafana.weekly_reports_sliding w on r.id = w.report_id\n\twhere\n\t--  replace(report, '\\\\u0000', ' ')::jsonb ? 'leaderboard'\n\t    replace(r.report, E'\\\\u0000', ' ')::jsonb#>'{leaderboard}' != 'false'\n\tand\n\t\tdate_trunc('day', daily_window) = date_trunc('day', now() - interval '1 day')\n\t--date_trunc('day', daily_window) = '2021-06-14'\n)\nselect\n  cluster_id id_internal,\n\tsubstring(ts.cluster_id, 1, 8) cluster_id,\n\tage(date_trunc('day', ts.created)) as \"Age\",\n\tround(ts.total_bytes / POWER(1024.0, 4)) total_tb, \n\tround(ts.total_used_bytes / POWER(1024.0, 4)) total_used_tb,\n\tts.osd_count,\n\tlc.organization as \"Organization\",\n\tlc.description as \"Description\",\n\tlc.contact as \"Contact\"\n\t--* \nfrom grafana.ts_cluster ts,\n\t leaderboard_clusters lc\nwhere \n--\tts.cluster_id = lc.cluster_id\n--and \n\tts.report_id = lc.report_id\nand ts.osd_count is not null -- some clusters report empty telemetry\norder by total_tb desc\n;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Ident channel opted-in - last week",
   "type": "table",
   "description": "All clusters reporting during the last 7 days that enabled 'ident' channel, but not necessarily enabled 'leaderboard'",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "-- leaderboard for all clusters enabled 'ident' channel, but not necessarily 'leadeboard':\nwith ident_clusters as (\n\tselect ts.report_id, ts.cluster_id--, array_agg(ts)\n\tfrom grafana.ts_cluster ts\n\tinner join grafana.weekly_reports_sliding w on ts.report_id = w.report_id\n\twhere channel_ident\n\tand date_trunc('day', w.daily_window) = date_trunc('day', now() - interval '1 day')\n\t--and ts.total_bytes > 0\n\t--ts > '2021-06-01'\n\t--group by cluster_id\n\t)\nselect --ic.report_id, \n  ic.cluster_id id_internal,\n\tsubstring(tsc.cluster_id, 1, 8) cluster_id,\n\tround(tsc.total_bytes / POWER(1024.0, 4)) total_tb, \n\tround(tsc.total_used_bytes / POWER(1024.0, 4)) total_used_tb,\n\ttsc.osd_count--,\nfrom ident_clusters ic\ninner join grafana.ts_cluster tsc \non ic.report_id = tsc.report_id\n--where\n--    r.report_stamp > '2021-06-10'\nwhere\n\ttsc.osd_count is not null -- some clusters report empty telemetry\nand round(tsc.total_bytes / POWER(1024.0, 4)) > 0\norder by total_tb desc;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "All clusters- last week",
   "type": "table",
   "description": "All clusters reporting during the last 7 days",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "-- leaderboard for all clusters:\nwith all_clusters as (\n\tselect ts.report_id, ts.cluster_id--, array_agg(ts)\n\tfrom grafana.ts_cluster ts\n\tinner join grafana.weekly_reports_sliding w on ts.report_id = w.report_id\n\twhere --channel_ident\n\t--and \n\t  date_trunc('day', w.daily_window) = date_trunc('day', now() - interval '1 day')\n\t--and ts.total_bytes > 0\n\t--ts > '2021-06-01'\n\t--group by cluster_id\n\t)\nselect --ac.report_id, \n  ac.cluster_id id_internal,\n\tsubstring(tsc.cluster_id, 1, 8) cluster_id,\n\tround(tsc.total_bytes / POWER(1024.0, 4)) total_tb, \n\tround(tsc.total_used_bytes / POWER(1024.0, 4)) total_used_tb,\n\ttsc.osd_count--,\nfrom all_clusters ac\ninner join grafana.ts_cluster tsc \non ac.report_id = tsc.report_id\n--where\n--    r.report_stamp > '2021-06-10'\nwhere\n\ttsc.osd_count is not null -- some clusters report empty telemetry\nand round(tsc.total_bytes / POWER(1024.0, 4)) > 0\norder by total_tb desc;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}