{
 "title": "Telemetry",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "display", "label": "Display by", "query": "Major,Minor" },
   {
    "name": "major",
    "label": "Major",
    "query": "select\n  replace(concat(version, '  --  ', name), 'Dev  --  ', 'Dev') as __text,\n  version as __value\nfrom grafana.version_to_name;"
   },
   {
    "name": "minor",
    "label": "Minor",
    "query": "/*select\n\tdistinct(SPLIT_PART(value, '.', '1')) major\nfrom\n\tgrafana.metadata\nwhere\n\tattr='ceph_version_norm'\norder BY\n\tmajor;\n*/\n\nselect\n        distinct(value)\nfrom\n\tgrafana.metadata\nwhere\n\tattr='ceph_version_norm'\nand\n      SPLIT_PART(value, '.', '1') in ($major);\n"
   },
   { "name": "daemons", "label": "Daemons", "query": "osd,mon" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding-top:20px\">Dropdown usage:</div>\n<div style=\"color:#32d1df\">\nThese dropdowns affect 'Version by Cluster Count' and 'Version by Daemon Count' charts below.\n<br>Stats can be displayed by either major or minor versions. \n<br>'Major' dropdown filters the options of 'Minor' dropdown. \n<br>Stats by either 'Major' or 'Minor' dropdowns are also filtered by 'Daemons' dropdown.\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": {
    "content": "<div style=\"padding-top:50px;font-size:30px;\">\n  <a href=\"/d/8zJ68iWnk/leaderboard?orgId=1\" style=\"color:#32d1df\">\n      Leaderboard\n  </a>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 18, "y": 0 },
   "options": {
    "content": "<div style=\"padding-top:50px;font-size:30px;\">\n  <a href=\"\n  /d/OVxgLWiGz/\" style=\"color:#32d1df\">\n      Devices Dashboard\n  </a>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "OSD Count",
   "type": "stat",
   "description": "Counting all OSDs from clusters reporting during the last 7 days",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(c.osd_count) as \"OSD Count\"\nfrom grafana.weekly_reports_sliding w\ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere daily_window >= CURRENT_DATE - INTERVAL '1' DAY\ngroup by daily_window;"
    }
   ]
  },
  {
   "title": "Active Clusters",
   "type": "stat",
   "description": "Counting all clusters reporting during the last 7 days",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- no need to count distinct since cluster_id is already distinct per day\nselect count(c.cluster_id) total\nfrom grafana.weekly_reports_sliding w\ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere daily_window >= CURRENT_DATE - INTERVAL '1' DAY\ngroup by daily_window;"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Counting capacity of all clusters reporting during the last 7 days",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(c.TOTAL_BYTES) total\nfrom grafana.weekly_reports_sliding w\ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere daily_window >= CURRENT_DATE - INTERVAL '1' DAY\ngroup by daily_window;"
    }
   ]
  },
  {
   "title": "Version by Cluster Count",
   "type": "graph",
   "description": "Takes the latest report of each cluster per week, and counts the versions by cluster count:\nEach cluster contributes '1', regardless of number of daemons:\nIf 2/200 daemons are v1 and 198 v2, then we add in .01 for v1; and .99 for v2.\nDisplays only the checked options from 'Major' or 'Minor' dropdowns on the top left corner of this page.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH\n-- Get the matching metadata stats, per the above report (latest, weekly)\nweekly_metadata AS (\n  SELECT\n    daily_window, grafana.metadata.*\n  FROM\n    grafana.metadata\n  INNER JOIN\n    grafana.WEEKLY_REPORTS_SLIDING w ON w.report_id = grafana.metadata.report_id\n  WHERE\n    attr='ceph_version_norm'\n),\n-- This retrieves total daemons per report (which is of a cluster, per week)\nweekly_cluster_daemons AS ( \n  SELECT report_id, sum(total) sum_daemons\n  FROM grafana.metadata\n  WHERE attr='ceph_version_norm'\n  and entity in ($daemons)\n  GROUP BY report_id\n)\nselect\n  $__timeGroup(wm.daily_window, '1d', 0),\n  -- daily_window as time, \n  CASE\n \tWHEN '$display' = 'Major' then\n          SPLIT_PART(value, '.', 1)\n    ELSE value\n  END as metric,\n  --wm.value as metric, \n  sum(wm.total / CAST(cd.sum_daemons AS real))  \nfrom weekly_metadata wm\ninner join weekly_cluster_daemons cd \nON wm.report_id = cd.report_id\nwhere $__timeFilter(daily_window) \nand case when '$display'='Major' then\n            SPLIT_PART(value, '.', 1)\n          else value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\nelse Array[$minor] end))\n-- and value in ($minor) \nand entity in ($daemons)\nGROUP by daily_window, 2\norder by daily_window, 2;\n-- order by 2, daily_window;"
    }
   ]
  },
  {
   "title": "Version by Daemon Count",
   "type": "graph",
   "description": "Takes the latest report of each cluster per week, and counts the versions by daemons. Displays only the checked options from 'Major' or 'Minor' dropdowns on the top left corner of this page.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select  $__timeGroup(w.daily_window, '1d', 0),\n        --w.daily_window as time,\n        --value as metric,\n        CASE\n            WHEN '$display' = 'Major' then\n              SPLIT_PART(value, '.', 1) \n            else value\n        end as metric,\n        sum(total)\nfrom grafana.weekly_reports_sliding w\ninner join\n        grafana.metadata\n        on w.report_id = grafana.metadata.report_id\nwhere \n    attr='ceph_version_norm'\n    and $__timeFilter(w.daily_window)\n    --and value in ($major)\n    and case when '$display'='Major' then\n            SPLIT_PART(value, '.', 1)\n          else value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\n    else Array[$minor] end))\n    and entity in ($daemons)\ngroup by w.daily_window, 2\norder by w.daily_window, 2;\n-- order by 2, w.daily_window;"
    }
   ]
  },
  {
   "title": "Active Clusters by a Daily Sliding Window of a Week",
   "type": "graph",
   "description": "Every day shows a count of all distinct clusters reporting over a past week.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, count(*) as \"Active Clusters\"\nfrom grafana.weekly_reports_sliding w\ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;\n\n\n/*\n-- weekly_reports_sliding: returns a table with rows of \"days\" (acutally called ts),\n-- and for each \"days\" returns all the reports of all clusters\n-- that reported in the week preceeding the day, but only 1 report per cluster - the newest.\nwith weekly_reports_sliding as (\n  select distinct on(days, cluster_id) days ts, report_id \n  -- generate_series generates a table with a single column 'days' (since 'day' is a reserved keyword) \n  -- and 365 rows;\n  from grafana.ts_cluster c, GENERATE_SERIES(now()::date - 365, now()::date, interval '1' day) days\n  where c.ts between days - interval '7' day AND days + interval '1' day\n  order by days, cluster_id, ts desc\n)\n-- clusters reporting\nselect ts as time, count(*) from weekly_reports_sliding\ngroup by ts\norder by ts;\n*/"
    }
   ]
  },
  {
   "title": "OSD Count by a Daily Sliding Window of a Week",
   "type": "graph",
   "description": "Every day shows an OSD count of all distinct clusters reporting over a past week.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n        daily_window as time,\n        sum(c.osd_count) as \"OSD count\"\nFROM\n        grafana.weekly_reports_sliding w\nINNER JOIN \n        grafana.ts_cluster c \n        ON \n        w.report_id = c.report_id\nGROUP BY \n        daily_window\nORDER BY \n        daily_window;"
    }
   ]
  },
  {
   "title": "Total Capacity by a Daily Sliding Window of a Week",
   "type": "graph",
   "description": "Every day shows a total bytes count of all distinct clusters reporting over a past week.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, sum(c.TOTAL_BYTES) as \"Total\", sum(c.TOTAL_USED_BYTES) as \"Used\"\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "Total Capacity by Version",
   "type": "graph",
   "description": "Every day shows a total bytes count of all distinct clusters reporting over a past week. We aggregate the number of total bytes according to the osd versions.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "with cpo as ( --capacity_per_osd\n\tselect\n\t  --$__timeGroup(w.daily_window, '1d', 0),\n\t\tw.daily_window, -- as time,\n\t\tc.report_id,\n\t\t--c.osd_count,\n\t\tc.TOTAL_BYTES / c.osd_count::real as \"total_bytes_per_osd\"\n\t\t--, c.TOTAL_USED_BYTES / c.osd_count::real as \"total_used_bytes_per_osd\"\n\t\t--sum(c.TOTAL_BYTES) as \"Total\",\n\t\t--sum(c.TOTAL_USED_BYTES) as \"Used\"\n\t\t--c.TOTAL_BYTES as \"Total\",\n\t\t--c.TOTAL_USED_BYTES as \"Used\"\n\tfrom grafana.weekly_reports_sliding w \n\tinner join grafana.ts_cluster c on w.report_id = c.report_id\n\twhere osd_count > 0\n\t--and c.TOTAL_BYTES > 0\n\t--group by daily_window\n\t--order by daily_window\n)\nselect --*,\n\t--cpo.daily_window as time,\n\t$__timeGroup(cpo.daily_window, '1d', 0),\n\t--gm.value as metric,\n\tCASE\n    WHEN '$display' = 'Major' then\n      SPLIT_PART(gm.value, '.', 1) \n    else gm.value\n  end as metric,\n\t-- gm.total is the total number of daemons with that attribute\n\tsum(gm.total * total_bytes_per_osd) as \"Total bytes\"--, -- total bytes for all osds reporting this ceph_version_norm\n\t--, sum(gm.total * total_used_bytes_per_osd) as \"Total used bytes\" -- -- total used bytes for all osds reporting this ceph_version_norm\nfrom cpo\ninner join grafana.metadata gm on cpo.report_id = gm.report_id \nwhere gm.attr = 'ceph_version_norm'\nand case when '$display'='Major' then\n            SPLIT_PART(gm.value, '.', 1)\n          else gm.value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\n    else Array[$minor] end))\nand gm.entity = 'osd'\ngroup by 1, 2\norder by 1; --upo.daily_window;\n"
    }
   ]
  },
  {
   "title": "Total Used Capacity by Version",
   "type": "graph",
   "description": "Every day shows a total bytes count of all distinct clusters reporting over a past week. We aggregate the number of total used bytes according to the osd versions.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "with cpo as ( --capacity_per_osd\n\tselect\n\t  --$__timeGroup(w.daily_window, '1d', 0),\n\t\tw.daily_window, -- as time,\n\t\tc.report_id,\n\t\t--c.osd_count,\n\t\t-- c.TOTAL_BYTES / c.osd_count::real as \"total_bytes_per_osd\",\n\t\tc.TOTAL_USED_BYTES / c.osd_count::real as \"total_used_bytes_per_osd\"\n\t\t--sum(c.TOTAL_BYTES) as \"Total\",\n\t\t--sum(c.TOTAL_USED_BYTES) as \"Used\"\n\t\t--c.TOTAL_BYTES as \"Total\",\n\t\t--c.TOTAL_USED_BYTES as \"Used\"\n\tfrom grafana.weekly_reports_sliding w \n\tinner join grafana.ts_cluster c on w.report_id = c.report_id\n\twhere osd_count > 0\n\t--and c.TOTAL_BYTES > 0\n\t--group by daily_window\n\t--order by daily_window\n)\nselect --*,\n\t--cpo.daily_window as time,\n\t$__timeGroup(cpo.daily_window, '1d', 0),\n\t--gm.value as metric,\n\tCASE\n    WHEN '$display' = 'Major' then\n      SPLIT_PART(gm.value, '.', 1) \n    else gm.value\n  end as metric,\n\t-- gm.total is the total number of daemons with that attribute\n\t--sum(gm.total * total_bytes_per_osd) as \"Total bytes\"--, -- total bytes for all osds reporting this ceph_version_norm\n\tsum(gm.total * total_used_bytes_per_osd) as \"Total used bytes\" -- -- total used bytes for all osds reporting this ceph_version_norm\nfrom cpo\ninner join grafana.metadata gm on cpo.report_id = gm.report_id \nwhere gm.attr = 'ceph_version_norm'\nand case when '$display'='Major' then\n            SPLIT_PART(gm.value, '.', 1)\n          else gm.value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\n    else Array[$minor] end))\nand gm.entity = 'osd'\ngroup by 1, 2\norder by 1; --cpo.daily_window;\n\n/*\nselect daily_window as time, sum(c.TOTAL_BYTES) as \"Total\", sum(c.TOTAL_USED_BYTES) as \"Used\"\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;\n*/"
    }
   ]
  },
  {
   "title": "Cluster Distribution by Total Capacity",
   "type": "heatmap",
   "description": "X axis is a daily sliding window of a week;\nY axis is total capacity;\nColor intensity represents the number of clusters within this total capacity range.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "rawSql": "select\n\tw.DAILY_WINDOW as time,\n\tc.total_bytes / 1024 / 1024 / 1024 gb\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.ts_cluster c\non\n\tw.REPORT_ID = c.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\norder by\n\tw.DAILY_WINDOW;"
    }
   ]
  },
  {
   "title": "Cluster Distribution by Total Capacity",
   "type": "heatmap",
   "description": "X axis is a daily sliding window of a week;\nY axis is total capacity;\nColor intensity represents the number of clusters within this total capacity range.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "rawSql": "select\n\tw.DAILY_WINDOW as time,\n\tc.total_bytes / 1024 / 1024 / 1024 gb\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.ts_cluster c\non\n\tw.REPORT_ID = c.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\norder by\n\tw.DAILY_WINDOW;"
    }
   ]
  },
  {
   "title": "Cluster Distribution by Total Used Capacity",
   "type": "heatmap",
   "description": "X axis is a daily sliding window of a week;\nY axis is total used capacity;\nColor intensity represents the number of clusters within this total used capacity range.",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "rawSql": "select\n\tw.DAILY_WINDOW as time,\n\tc.total_used_bytes / 1024 / 1024 / 1024 gb\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.ts_cluster c\non\n\tw.REPORT_ID = c.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\norder by\n\tw.DAILY_WINDOW;"
    }
   ]
  },
  {
   "title": "Cluster Distribution by OSD Count",
   "type": "heatmap",
   "description": "X axis is a daily sliding window of a week;\nY axis is OSD count;\nColor intensity represents the number of clusters which have this OSD count.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "rawSql": "select\n\tw.DAILY_WINDOW as time,\n\tc.OSD_COUNT\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.ts_cluster c\non\n\tw.REPORT_ID = c.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\norder by\n\tw.DAILY_WINDOW;"
    }
   ]
  },
  {
   "title": "More Charts",
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 149 },
   "options": {
    "content": "\n# [See more capacity density charts](/d/Pb90AgCWk/capacity-density?orgId=1)\n\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}