{
 "title": "Capacity Density",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Cluster / TiB - Capacity Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(daily_window, '1d', 0), \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "Cluster / TiB  < 1 PiB  - Capacity Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(daily_window, '1d', 0), \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real < 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "Cluster / TiB  > 1 PiB  - Capacity Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select $__timeGroup(daily_window, '1d', 0), \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real > 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "OSD / Host  -  Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select \ndaily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.osd_count / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.osd_count / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.osd_count / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.osd_count / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "OSD / Host  <  1 PiB  -  Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.osd_count / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.osd_count / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.osd_count / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.osd_count / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real < 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "OSD / Host  >  1 PiB  -  Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.osd_count / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.osd_count / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.osd_count / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.osd_count / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real > 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / OSD - Capacity per OSD Count Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.osd_count::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.osd_count::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.osd_count::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.osd_count::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.osd_count > 0\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / OSD  < 1 PiB  -  Capacity per OSD Count Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.osd_count::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.osd_count::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.osd_count::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.osd_count::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.osd_count > 0\nand c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real < 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / OSD  > 1 PiB  -  Capacity per OSD Count Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.osd_count::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.osd_count::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.osd_count::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.osd_count::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.osd_count > 0\nand c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real > 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / Host - Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select \ndaily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / Host  <  1 PiB  -  Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real < 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  },
  {
   "title": "TiB / Host  >  1 PiB  -  Capacity per Hosts Percentiles by a Daily Sliding Window of a Week",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "rawSql": "select daily_window as time, \nPERCENTILE_DISC(0.25) within group (order by c.total_bytes / c.hosts_num::real) as p25,\nPERCENTILE_DISC(0.50) within group (order by c.total_bytes / c.hosts_num::real) as p50,\nPERCENTILE_DISC(0.75) within group (order by c.total_bytes / c.hosts_num::real) as p75,\nPERCENTILE_DISC(1) within group (order by c.total_bytes / c.hosts_num::real) as p100\nfrom grafana.weekly_reports_sliding w \ninner join grafana.ts_cluster c on w.report_id = c.report_id\nwhere c.total_bytes / 1024 / 1024 / 1024 / 1024 / 1024::real > 1\ngroup by daily_window\norder by daily_window;"
    }
   ]
  }
 ]
}