{
 "title": "Objectstore",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "display", "label": "Display by", "query": "Major,Minor" },
   {
    "name": "major",
    "label": "Major",
    "query": "select\n  replace(concat(version, '  --  ', name), 'Dev  --  ', 'Dev') as __text,\n  version as __value\nfrom grafana.version_to_name;"
   },
   {
    "name": "minor",
    "label": "Minor",
    "query": "/*select\n\tdistinct(SPLIT_PART(value, '.', '1')) major\nfrom\n\tgrafana.metadata\nwhere\n\tattr='ceph_version_norm'\norder BY\n\tmajor;\n*/\n\nselect\n        distinct(value)\nfrom\n\tgrafana.metadata\nwhere\n\tattr='ceph_version_norm'\nand\n      SPLIT_PART(value, '.', '1') in ($major);\n"
   }
  ]
 },
 "panels": [
  {
   "title": "OSD count  by objectstore and version for  ${__to:date:YYYY-MM-DD}",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n        CASE\n            WHEN '$display' = 'Major' then\n              SPLIT_PART(md_ver.value, '.', 1)\n            else md_ver.value\n        end as version,\n        md_obj.value objectstore,\n--        ARRAY_POSITION(Array['filestore', 'bluestore', 'memstore'], md_obj.value::text) color,\n        sum(md_ver.total) OSDs\nfrom\n        grafana.weekly_reports_sliding w\ninner join\n        grafana.metadata md_ver\n        on w.report_id = md_ver.report_id and md_ver.attr = 'ceph_version_norm' AND md_ver.entity = 'osd'\ninner join\n        grafana.metadata md_obj\n        on w.report_id = md_obj.report_id and md_obj.attr = 'osd_objectstore'\nwhere \n    w.DAILY_WINDOW BETWEEN $__timeTo()::timestamp - interval '1 day' AND $__timeTo()::timestamp\n    and case when '$display'='Major' then\n            SPLIT_PART(md_ver.value, '.', 1)\n          else md_ver.value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\n    else Array[$minor] end))\n--    and entity in ($daemons)\ngroup by 1, md_obj.value\norder by 1;\n"
    }
   ]
  },
  {
   "title": "Cluster count by version and objectstore for  ${__to:date:YYYY-MM-DD}",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "\nWITH\n-- Get the matching metadata stats, per the above report (latest, weekly)\nweekly_metadata AS (\n  SELECT\n    daily_window, grafana.metadata.*\n  FROM\n    grafana.metadata\n  INNER JOIN\n    grafana.WEEKLY_REPORTS_SLIDING w ON w.report_id = grafana.metadata.report_id\n  WHERE\n    attr='ceph_version_norm'\n),\n-- This retrieves total daemons per report (which is of a cluster, per week)\nweekly_cluster_daemons AS ( \n  SELECT report_id, sum(total) sum_daemons\n  FROM grafana.metadata\n  WHERE attr='ceph_version_norm'\n  AND entity = 'osd'\n  GROUP BY report_id\n)\nselect\n  -- daily_window as time, \n  CASE\n \tWHEN '$display' = 'Major' then\n          SPLIT_PART(wm.value, '.', 1)\n    ELSE wm.value\n  END as version,\n  --wm.value as metric,\n  md_obj.value as objectstore,\n  -- Sum the OSDs (attr='ceph_version_norm') total' and not the objectstore (attr='osd_objectstore') 'total' \n  sum(wm.total / CAST(cd.sum_daemons AS real)) as clusters\nfrom weekly_metadata wm\ninner join weekly_cluster_daemons cd \nON wm.report_id = cd.report_id\nINNER JOIN grafana.metadata md_obj ON md_obj.report_id = wm.report_id \nwhere $__timeFilter(daily_window)\nAND md_obj.attr = 'osd_objectstore'\nand case when '$display'='Major' then\n            SPLIT_PART(wm.value, '.', 1)\n          else wm.value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\nelse Array[$minor] end))\n-- and value in ($minor) \nand wm.entity = 'osd'\nAND daily_window BETWEEN $__timeTo()::timestamp - interval '1 day' AND $__timeTo()::timestamp\nGROUP by daily_window, 1, md_obj.value\norder by 1, daily_window;\n"
    }
   ]
  },
  {
   "title": "Active clusters",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select\n\t--*\n\tw.DAILY_WINDOW as time,\n\tcount(*) \"Active clusters\"\n\t--count(distinct(cluster_id))\n\t--w.DAILY_WINDOW,\n\t--w.report_id--,\n\t--percentile_cont(0.5) within group (order by num_images) as med,\n\t--round(avg(c.num_images)) as avg,\n\t--count(c.num_images),\n\t--count(c.pool_idx),\n\t--sum(c.num_images) as total_images_per_cluster--,\n\t--max(c.num_images)\n\t--count(distinct(cluster_id))\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.ts_cluster c\n\t--grafana.rbd_pool c -- 'c' for cluster\non\n\tw.REPORT_ID = c.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\nGROUP BY w.daily_window--, w.report_id\norder by\n\tw.DAILY_WINDOW;\n"
    },
    {
     "rawSql": "select\n\t--*\n\tw.DAILY_WINDOW as time,\n\tcount(*) \"Active clusters reporting objectstore\"\n\t--count(distinct(cluster_id))\n\t--w.DAILY_WINDOW,\n\t--w.report_id--,\n\t--percentile_cont(0.5) within group (order by num_images) as med,\n\t--round(avg(c.num_images)) as avg,\n\t--count(c.num_images),\n\t--count(c.pool_idx),\n\t--sum(c.num_images) as total_images_per_cluster--,\n\t--max(c.num_images)\n\t--count(distinct(cluster_id))\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.metadata md\n\t--grafana.rbd_pool c -- 'c' for cluster\non\n\tw.REPORT_ID = md.REPORT_ID\nWHERE\n  $__timeFilter(w.DAILY_WINDOW)\nAND\n  md.attr = 'osd_objectstore'\nGROUP BY w.daily_window--, w.report_id\norder by\n\tw.DAILY_WINDOW;\n"
    }
   ]
  },
  {
   "title": "OSD count by objectstore across all versions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(w.DAILY_WINDOW, '1d', 0),\n  sum(md.total) as value,\n  value as metric\nfrom\n\tgrafana.WEEKLY_REPORTS_SLIDING w\ninner join \n\tgrafana.metadata md \non\n\tw.REPORT_ID = md.REPORT_ID\nWHERE\n--  $__timeFilter(w.DAILY_WINDOW)\n  w.DAILY_WINDOW BETWEEN $__timeFrom()::timestamp - interval '1 day' AND $__timeTo()\n  AND md.attr = 'osd_objectstore'\nGROUP BY w.daily_window, md.value\norder by\n\tw.DAILY_WINDOW;\n"
    }
   ]
  },
  {
   "title": "Clusters with multiple objectstore types",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "--select\n--  $__timeGroup(w.DAILY_WINDOW, '1d', 0),\nwith mixed as (\n  SELECT md.report_id, wrs.daily_window, count(distinct(value)) val\n  FROM grafana.metadata md\n  INNER JOIN grafana.weekly_reports_sliding wrs ON md.report_id = wrs.report_id\n  WHERE\n  \t$__timeFilter(wrs.daily_window)\n  \tAND md.attr = 'osd_objectstore'\n  GROUP BY md.report_id, wrs.daily_window \n  HAVING count(distinct(value)) > 1  \n)\nselect daily_window as time, count(*) from mixed\nGROUP BY daily_window \nORDER BY daily_window \n"
    }
   ]
  },
  {
   "title": "OSD filestore/bluestore ratio",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "with\n -- extract number of bluestore OSDs per day\nmd_bs AS (\n\tselect\n\t\t-- $__timeGroup(w.DAILY_WINDOW, '1d', 0),\n \t\tw.DAILY_WINDOW,\n  \t\tsum(md.total) as value\n\tfrom\n\t\tgrafana.WEEKLY_REPORTS_SLIDING w\n\tinner join \n\t\tgrafana.metadata md \n\ton\n\t\tw.REPORT_ID = md.REPORT_ID\n\tWHERE attr='osd_objectstore' AND value = 'bluestore'\n\tGROUP BY w.DAILY_WINDOW\n),\nmd_fs AS (\n\tselect\n\t\t-- $__timeGroup(w.DAILY_WINDOW, '1d', 0),\n\t\tw.DAILY_WINDOW,\n\t\tsum(md.total) as value\n\tfrom\n\t\tgrafana.WEEKLY_REPORTS_SLIDING w\n\tinner join \n\t\tgrafana.metadata md \n\ton\n\t\tw.REPORT_ID = md.REPORT_ID\n\tWHERE attr='osd_objectstore' AND value = 'filestore'\n\tGROUP BY w.DAILY_WINDOW\n)\nselect\n  $__timeGroup(md_fs.DAILY_WINDOW, '1d', 0),\n  md_fs.value::real / md_bs.value ratio\nfrom md_fs\ninner join md_bs on md_fs.DAILY_WINDOW = md_bs.DAILY_WINDOW\nwhere md_fs.DAILY_WINDOW BETWEEN $__timeFrom()::timestamp - interval '1 day' AND $__timeTo()\norder by md_fs.DAILY_WINDOW"
    }
   ]
  },
  {
   "title": "OSD count by objectstore and version",
   "type": "graph",
   "description": "Takes the latest report of each cluster per week, and counts the versions by daemons. Displays only the checked options from 'Major' or 'Minor' dropdowns on the top left corner of this page.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select  $__timeGroup(w.daily_window, '1d', 0),\n        CASE\n            WHEN '$display' = 'Major' then\n              concat(SPLIT_PART(md_ver.value, '.', 1), ' ', md_obj.value) \n            else concat(md_ver.value, ' ', md_obj.value)\n        end as metric,\n        sum(md_ver.total)\nfrom\n        grafana.weekly_reports_sliding w\ninner join\n        grafana.metadata md_ver\n        on w.report_id = md_ver.report_id and md_ver.attr = 'ceph_version_norm' AND md_ver.entity = 'osd'\ninner join\n        grafana.metadata md_obj\n        on w.report_id = md_obj.report_id and md_obj.attr = 'osd_objectstore'\nwhere \n    w.DAILY_WINDOW BETWEEN $__timeFrom()::timestamp - interval '1 day' AND $__timeTo()\n    and case when '$display'='Major' then\n            SPLIT_PART(md_ver.value, '.', 1)\n          else md_ver.value end\n          in\n          (select unnest(case when '$display'='Major' then Array[$major]\n    else Array[$minor] end))\n--    and entity in ($daemons)\ngroup by w.daily_window, 2, md_obj.value\norder by 2, w.daily_window;"
    }
   ]
  }
 ]
}