{
 "title": "Failure Prediction",
 "time": { "from": "now-6M", "to": "now" },
 "panels": [
  {
   "title": "Devices eligible for prediction",
   "type": "stat",
   "description": "Devices that have (at any point in time) 6-12 valid telemetry reports (i.e. which do not contain smartctl errors).",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(device_id))\nfrom device.prediction_result;"
    }
   ]
  },
  {
   "title": "Devices which are supported by the model",
   "type": "stat",
   "description": "Distinct devices count of all devices which the model supported at some point",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(device_id))\nfrom device.prediction_result\nwhere result != 'Model does not support this vendor' and result != 'Model failed';"
    }
   ]
  },
  {
   "title": "Devices with 'Warning' or 'Bad' prediction",
   "type": "stat",
   "description": "Distinct devices count of all devices which had 'Warning' or 'Bad' as a prediction result at some point",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(device_id))\nfrom device.prediction_result\nwhere\n      result = 'Warning'\n  or result = 'Bad';"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Devices with alerts",
   "type": "table",
   "description": "Model returned 'Warning' or 'Bad' at some point for these devices.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "-- Get all devices with alerting prediction result ('Warning' or 'Bad')\n-- with their full spec details \nselect\n\tdistinct on (device_id) device_id, ts::TEXT last_report, result,\n\tdevice.spec.vendor,\n\tdevice.spec.model,\n\tdevice.spec.type,\n\tdevice.spec.interface,\n\tdevice.spec.capacity--,\n\t--device.device.host_id -- remove this in a public dashboard\nfrom device.prediction_result\n\tinner join device.device on device.prediction_result.device_id = device.device.id\n\tinner join device.spec on device.device.spec_id = device.spec.id\nwhere device.prediction_result.device_id IN \n\t(\n\tselect distinct(device_id)--, max(ts) \n\tfrom device.prediction_result\n\twhere result = 'Warning'\n\tor result = 'Bad'\n\t) \norder by device_id, ts desc;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Device Failure Prediction Result",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "select\n\tdevice.device.id,\n\tdevice.spec.vendor,\n\tdevice.spec.model,\n\tdevice.spec.type,\n\tdevice.spec.interface,\n\tdevice.spec.capacity,\n\tdevice.prediction_result.result \"prediction\"\n\t--substring(device.prediction_result.result, length('PredictionResult.')) \"prediction\"\nfrom device.prediction_result\ninner join device.device on device.prediction_result.device_id = device.device.id\ninner join device.spec on device.device.spec_id = device.spec.id\nlimit 500;"
    }
   ]
  }
 ]
}