{
 "title": "Main",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "class",
    "label": "class",
    "query": "select distinct(class) from device.spec\nwhere device.spec.class != 'unknown';"
   },
   {
    "name": "vendor",
    "label": "vendor",
    "query": "select distinct(lower(vendor)) from device.spec\nwhere device.spec.class in ($class);"
   },
   {
    "name": "model",
    "label": "model",
    "query": "/*\nselect distinct(lower(model))\nfrom device.spec\nwhere vendor = $vendor\n*/\n\nselect\n        distinct(model)\nfrom\n\tdevice.spec\nwhere\n       --device.spec.class = 'normal'\n--and\n       lower(device.spec.vendor) in ($vendor);\n/*\nwhere\n\tattr='ceph_version_norm'\nand\n      SPLIT_PART(value, '.', '1') in ($major);\n*/"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Devices",
   "type": "stat",
   "description": "All active devices (reporting both valid and invalid telemetry)",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- TODO: check if it's still correct with the 'tomorrow' box\n    SELECT\n        COUNT(*) total\n    FROM\n        device.weekly_reports_sliding w\n\t\t    INNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\t\t    INNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding)\n        and device.spec.class in ($class)\n        and lower(device.spec.vendor) in ($vendor)\n        and device.spec.model in ($model);\n\n/*\n    SELECT\n        COUNT(*) total\n    FROM\n        device.weekly_reports_sliding w\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding);\n*/  "
    }
   ]
  },
  {
   "title": "With Valid Telemetry",
   "type": "stat",
   "description": "Active devices reporting valid telemetry",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "    SELECT\n        COUNT(*) total\n    FROM\n        device.weekly_reports_sliding w\n        --inner join device.ts_device on w.report_id = device.ts_device.report_id\n\t\tINNER JOIN device.ts_device ON w.report_id = device.ts_device.REPORT_ID\n\t\tINNER JOIN device.device ON device.ts_device.DEVICE_ID = device.device.id\n\t\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding)\n        and\n        device.ts_device.error is NULL -- meaning there's data in the report\n        and device.spec.class in ($class)\n        and lower(device.spec.vendor) in ($vendor)\n        and device.spec.model in ($model);\n/*\n-- TODO: check if it's still correct with the 'tomorrow' box\n    SELECT\n        COUNT(*) total\n    FROM\n        device.weekly_reports_sliding w\n        inner join\n        device.ts_device\n        on w.report_id = device.ts_device.report_id\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding)\n        and\n        device.ts_device.error is NULL; -- meaning there's data in the report\n*/"
    }
   ]
  },
  {
   "title": "Total Capacity",
   "type": "stat",
   "description": "Total capacity of all active devices",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "    SELECT\n   \t\tsum(capacity)\n    FROM\n        device.weekly_reports_sliding w\n\t\t    INNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\t\t    INNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding)\n        and device.spec.class in ($class)\n        and lower(device.spec.vendor) in ($vendor)\n        and device.spec.model in ($model);\n\n    \n/*\n    SELECT\n        COUNT(*) total\n    FROM\n        device.weekly_reports_sliding w\n    WHERE\n        daily_window = (SELECT MAX(daily_window) FROM device.weekly_reports_sliding);\n*/  "
    }
   ]
  },
  {
   "title": "Hosts - All-time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(host_id))\nfrom device.device d\ninner join device.spec s\non d.spec_id = s.id\nwhere \ns.class in ($class)\nand s.vendor in ($vendor)\n/*\nselect count(distinct(lower(model)))\nfrom device.spec\nwhere device.spec.class in ($class);\n*/"
    }
   ]
  },
  {
   "title": "Vendors - All-time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(lower(vendor)))\nfrom device.spec\nwhere \ndevice.spec.class in ($class);\n--device.spec.class = 'normal';"
    }
   ]
  },
  {
   "title": "Models - All-time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct(lower(model)))\nfrom device.spec\nwhere device.spec.class in ($class)\nand device.spec.vendor in ($vendor);"
    }
   ]
  },
  {
   "title": "Devices by Vendors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\t--count(*),\n\tdevice.spec.vendor as metric,\n\tcount(*)\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n  --where $__timeFilter(daily_window)\n  where daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  --and device.spec.class = 'normal'\n  and device.spec.class in ($class)\n  and device.spec.vendor in ($vendor)\n  and device.spec.model in ($model)\n  --and device.spec.class != 'unknown'\nGROUP BY\n\tw.daily_window, device.spec.vendor\n--ORDER BY w.daily_window, lower(device.spec.vendor);\nORDER BY --2, w.daily_window;\n  w.daily_window, 2;"
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "select\n  daily_window as time, \n  count(*) as \"Total\"\nfrom\n  device.weekly_reports_sliding w\ninner join\n  device.ts_device d on w.report_id = d.report_id\nwhere daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\ngroup by\n  daily_window\norder by\n  daily_window;\n"
    },
    {
     "rawSql": "select\n  daily_window as time, \n  count(*) as \"Reporting Invalid Telemetry\"\nfrom\n  device.weekly_reports_sliding w\ninner join\n  device.ts_device d on w.report_id = d.report_id\nwhere daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\nand d.error is not NULL -- meaning there's an error and the device is not reporting correctly\ngroup by\n  daily_window\norder by\n  daily_window;\n"
    },
    {
     "rawSql": "select\n  daily_window as time, \n  count(*) as \"Reporting Valid Telemetry\"\nfrom\n  device.weekly_reports_sliding w\ninner join\n  device.ts_device d on w.report_id = d.report_id\nwhere daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\nand d.error is  NULL\ngroup by\n  daily_window\norder by\n  daily_window;\n"
    }
   ]
  },
  {
   "title": "Distinct Hosts - $vendor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(distinct(device.device.host_id)) as \"Distinct Hosts\"\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n--where $__timeFilter(daily_window)\nwhere daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  and device.spec.class in ($class)\n  and device.spec.vendor in ($vendor)\n  and device.spec.model in ($model)\n  --and device.spec.type is not NULL\nGROUP BY\n\tw.daily_window\nORDER BY w.daily_window;\n"
    }
   ]
  },
  {
   "title": "Distinct Models - $vendor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(distinct(device.spec.model)) as \"Distinct Models\"\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n  where daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  and device.spec.vendor in ($vendor)\n  and device.spec.model in ($model)\n  --and device.spec.type is not NULL\nGROUP BY\n\tw.daily_window\nORDER BY w.daily_window;\n"
    }
   ]
  },
  {
   "title": "Devices by Types - $vendor",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(*),\n\tdevice.spec.type::TEXT as metric\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n--where $__timeFilter(daily_window)\nwhere daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  and device.spec.type is not NULL\n  and device.spec.vendor in ($vendor)\nGROUP BY\n\tw.daily_window, device.spec.type\nORDER BY w.daily_window;\n"
    }
   ]
  },
  {
   "title": "SSD Devices by Interface - $vendor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tdevice.spec.interface::TEXT as metric,\n\tcount(*)\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n  --where $__timeFilter(daily_window)\n  where daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  and\n      (device.spec.type::text = 'ssd'\n      or \n      device.spec.type::text = 'nvme')\n  and device.spec.vendor in ($vendor)\n  -- and device.spec.model in ($model)\nGROUP BY\n\tw.daily_window, device.spec.interface\nORDER BY w.daily_window, 2;\n"
    }
   ]
  },
  {
   "title": "HDD Devices by Interface - $vendor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(*),\n\tdevice.spec.interface::TEXT as metric\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n--where $__timeFilter(daily_window)\nWHERE daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\nAND device.spec.type::text = 'hdd'\nAND device.spec.vendor in ($vendor)\nGROUP BY\n\tw.daily_window, device.spec.interface\nORDER BY w.daily_window;\n"
    }
   ]
  },
  {
   "title": "Total Capacity - $vendor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "rawSql": "select\n  $__timeGroup(w.daily_window, '1d', 0),\n\tsum(capacity) as \"Total Capacity\" \nfrom\n  \tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON W.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n--where $__timeFilter(w.daily_window)\nWHERE daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\n  --and device.spec.type is not NULL\nAND device.spec.class in ($class)\nAND device.spec.vendor in ($vendor)\nAND device.spec.model in ($model)\nGROUP BY\n  daily_window\nORDER BY\n  daily_window;  \n"
    }
   ]
  },
  {
   "title": "Devices by HW RAID",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  -- FIX THIS\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tdevice.spec.vendor as metric,\n\tcount(*)\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n-- where $__timeFilter(daily_window)\nWHERE daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\nAND device.spec.class = 'hw_raid'\nGROUP BY\n\tw.daily_window, device.spec.vendor\nORDER BY w.daily_window, 2;\n"
    }
   ]
  },
  {
   "title": "Devices by Class",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(*),\n\tdevice.spec.class as metric\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.device ON w.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n--where $__timeFilter(daily_window)\nWHERE daily_window between $__timeFrom()::timestamptz - interval '1 day' and $__timeTo()\nAND device.spec.class != 'unknown'\nGROUP BY\n\tw.daily_window, device.spec.class\nORDER BY w.daily_window, device.spec.class;\n"
    }
   ]
  },
  {
   "title": "Invalid Telemetry Reports by Device Class",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n\t--w.daily_window as time,\n  $__timeGroup(w.daily_window, '1d', 0),\n\tcount(*) \"Empty Reports\",\n\tdevice.spec.class as metric\nFROM\n\tdevice.weekly_reports_sliding w\n\tINNER JOIN device.ts_device ON w.report_id = device.ts_device.REPORT_ID\n\tINNER JOIN device.device ON device.ts_device.DEVICE_ID = device.device.id\n\tINNER JOIN device.spec ON device.device.SPEC_ID = device.spec.id\n  where $__timeFilter(daily_window)\n  --and device.spec.class = 'normal'\n  and device.spec.class in ($class)\n  and device.ts_device.error is not NULL\nGROUP BY\n\tw.daily_window, device.spec.class\nORDER BY w.daily_window, device.spec.class;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 84 },
   "options": {
    "content": "<div style=\"padding-top:20px;font-size:30px\">\n  <a href=\"/d/GQDv4xmMz/tabular-data?orgId=1\">\n      See tabular panels\n  </a>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 84 },
   "options": {
    "content": "<div style=\"padding-top:20px; margin-bottom:20px;font-size:30px\">\n  <a href=\"https://docs.ceph.com/docs/master/mgr/telemetry/\">\n  Learn more about Ceph telemetry\n  </a>\n</div>\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  }
 ]
}