{
 "title": "Prediction by ID",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   { "name": "device_id", "label": "Device ID", "query": "1117" }
  ]
 },
 "panels": [
  {
   "title": "Prediction Result",
   "type": "graph",
   "description": "'1' == 'Good';    '2' == 'Warning';   '3' == 'Bad'",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "-- Add to the prediction_result table \n-- yesterday's result for this device_id\nselect\n\t--id,\n  --device_id,\n\tts as time,\n\tarray_position(array['Good', 'Warning', 'Bad', 'Model failed', 'Model does not support this vendor'], result) as result\n\t--result as metric\n\t/*curr_res,\n\tlag(result) over (\n\t\torder by ts asc\n\t) as prev_res */\nfrom device.prediction_result\nwhere device_id in ('$device_id') -- TODO change to variable\n;"
    }
   ]
  },
  {
   "title": "Prediction result flip points",
   "type": "table",
   "description": "Shows only cases where prediction result changed on consecutive days",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "-- Show only cases where prediction result changed the next day\nselect *\nfrom (\n  -- Add to the prediction_result table \n  -- yesterday's result for this device_id\n\tselect\n\t\tid,\n\t\tdevice_id,\n\t\tts::TEXT,\n\t\tresult curr_res,\n\t\tlag(result) over (\n\t\t\torder by ts asc\n\t\t) as prev_res\n\tfrom device.prediction_result\n\twhere device_id in ('$device_id')\n\t) res_window\nwhere res_window.curr_res != res_window.prev_res or prev_res is NULL \norder by ts;"
    }
   ]
  },
  {
   "title": "All prediction results for device_id   $device_id",
   "type": "table",
   "description": "Shows all prediction results for this device_id.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "-- Add to the prediction_result table \n-- yesterday's result for this device_id\nselect\n\tid,\n\tdevice_id,\n\tts::TEXT,\n\tresult /*curr_res,\n\tlag(result) over (\n\t\torder by ts asc\n\t) as prev_res */\nfrom device.prediction_result\nwhere device_id in ('$device_id') -- TODO change to variable\n;"
    }
   ]
  }
 ]
}